version: '3'

services:
  mysql:
    image: mysql:5.7.10
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gcp_circle_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  api:
    image: openjdk:8-jdk-alpine
    container_name: api-container
    depends_on:
      - mysql
    volumes:
      - ./api:/api
    ports:
      - 8080:8080
    working_dir: /api
    command: ./mvnw spring-boot:run
    networks:
      app_net:
        ipv4_address: 172.30.0.3

  ui:
    image: node:12.2.0-alpine
    container_name: ui-container
    tty: true
    depends_on:
      - api
    volumes:
      - ./ui:/ui
    ports:
      - 3000:3000
    working_dir: /ui
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    networks:
      app_net:
        ipv4_address: 172.30.0.4

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
